#pragma config(Sensor, S1,     COMPASS,        sensorI2CCustomFastSkipStates)
#pragma config(Motor,  motorB,          motorLeft,     tmotorNXT, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorNXT, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-compass.h"

void Arcade(int x, int y){
	int powY;
	int powX;
	int powRightMotor;
	int powLeftMotor;

	powY = y * 100 / 127;
	powX = x * 100 / 127;

	if (powX < 0)
	{
		powLeftMotor = powY * (100 + (2 * powX)) / 100;
		powRightMotor = powY;
	}
	else
	{
		powRightMotor = (powY * (100 - (2 * powX)) / 100);
		powLeftMotor = powY;
	}

	motor[motorRight] = powRightMotor;
	motor[motorLeft] = powLeftMotor;
}


task main()
{
	while (true)
	{
		getJoystickSettings(joystick);
		Arcade(joystick.joy1_x1, joystick.joy1_y1);
	}
}
